### ISSUE TITLE
Issue with pip-compile resolver

### ISSUE THREAD

**Issue by NicolaDonelli** [NicolaDonelli/py4ai-core#31]
The resolver that will be used by default by `pip-compile` will be `backtracking`.
With this resolver constraints will only be allowed to take the form of a package name and a version specifier. In particular we currently have a couple of extra dependencies in `requirements_dev.txt` and this will cause issues since `requirements_dev.txt` are used as constraints when building `requirements.txt`.

I'd propose, as a temporary patch, to restrict pip-tools version in `requirements_dev.in` to `pip-tools>=6.6.2,<7.0.0`.
But we should start thinking how to definitely solve this issue allowing for newer versions of pip-tools.

**Comment by deusebio** [comment]
What about switching to poetry? I'm starting to grow fond of it...

**Comment by NicolaDonelli** [comment]
I didn't have enough time to check it yet...

**Comment by deusebio** [comment]
> I'd propose, as a temporary patch, to restrict pip-tools version in requirements_dev.in to pip-tools>=6.6.2,<7.0.0.
> But we should start thinking how to definitely solve this issue allowing for newer versions of pip-tools.

Yes. That's fine. We can restrict pip-tools for the time being, while thinking about switching to poetry in the medium/long term
