### ISSUE TITLE
Update Dockerfile

### ISSUE THREAD

**Issue by NicolaDonelli** [NicolaDonelli/py4ai-core#32]
I think it could be more useful to update current Dockerfile to:

```
# syntax=docker/dockerfile:1

ARG  PY_VERSION=3.7
FROM python:${PY_VERSION}-buster

WORKDIR /py4ai-core

# RUN apt-get update && apt-get upgrade -y && apt-get install make git gcc libpq-dev -y --no-install-recommends

COPY requirements/requirements.in requirements/requirements.in
COPY requirements/requirements_dev.in requirements/requirements_dev.in
COPY LICENSE MANIFEST.in versioneer.py setup.py pyproject.toml README.md Makefile ./
COPY .git .git
COPY py4ai py4ai
COPY tests tests

RUN addgroup --system tester && adduser --system --group tester
RUN chown -R tester:tester /py4ai-core

# change to the tester user: switch to a non-root user is a best practice.
USER tester
ENV PATH ${PATH}:/home/tester/.local/bin

CMD make checks
```

This would allow us to easily test our package with different python versions (which is the most common usage I make of containers in this project).

If we find a value in keeping a python entrypoint to che container I'd suggest instead this solution:

```
# syntax=docker/dockerfile:1

ARG PY_VERSION=3.7
FROM python:${PY_VERSION}-buster as builder

WORKDIR /py4ai-core

COPY requirements/requirements.in requirements/requirements.in
COPY requirements/requirements_dev.txt requirements/requirements_dev.txt
COPY LICENSE MANIFEST.in versioneer.py setup.py pyproject.toml README.md Makefile ./
COPY .git .git
COPY py4ai py4ai
COPY tests tests
RUN addgroup --system tester && adduser --system --group tester
RUN chown -R tester:tester /py4ai-core
USER tester
RUN make checks

FROM python:${PY_VERSION}-slim-buster
WORKDIR /py4ai-core
COPY --from=builder /py4ai-core/dist /py4ai-core/dist
RUN addgroup --system runner && adduser --system --group runner
RUN chown -R runner:runner /py4ai-core
USER runner
RUN ls -t ./dist/*.tar.gz | xargs pip install
ENTRYPOINT ["python"]
```

**Comment by deusebio** [comment]
I'm totally up for adding the arguments to be able to build under different python versions, parametrically!

Also, I kinda liked the two-stage build we had, with the image that is built only having minimal dependencies (not the test ones) 

The two things are orthogonal and we could have both actually (parametric python version input AND minimal docker image with two-stage build). Why are you proposing a larger refactoring of the Dockerfile?

**Comment by NicolaDonelli** [comment]
Actually the main use I found for Docker in this context was exactly to test the package under different python versions (and, maybe, Operating Systems). Thus I found a little bit useless the second build with minimal requirements: I never felt the need to actually do something different than testing the package in a different environment... 
What use case do you have in mind?

**Comment by NicolaDonelli** [comment]
For what it takes copying .git folder in the container the reason is that we use versioneer to handle semantic versioning and it  gets the version number from the git tag. Thus we need to have that information in the container to correctly version the pacakge. 
Not having it is no real big deal since what happens in that case is simply that we will always have 0.0.0 (or something similar) as version number when building package in the container, but it kinda hurt my sight not seeing the correct version number in the logs.

**Comment by deusebio** [comment]
> Actually the main use I found for Docker in this context was exactly to test the package under different python versions (and, maybe, Operating Systems). Thus I found a little bit useless the second build with minimal requirements: I never felt the need to actually do something different than testing the package in a different environment...
> What use case do you have in mind?

Well, it is to have a functioning environment where to use the package. I agree that if this would be a direct application (with a rest API and/or services embedded), that would be more relevant. But yet, I believe it is a good practice to have a two-stage build, where in the first one you build and test the package, while in the second you only install the required dependencies and the application itself. I understand It is not as crucial as in other contexts, but why not. I don't see extra complexity in doing this, and indeed the images we produce are actually smaller. 

> Not having it is no real big deal since what happens in that case is simply that we will always have 0.0.0 (or something similar) as version number when building package in the container

BTW, the version could rather be embedded in the version of the docker container which would show up as "py4ai:x.y.z"

**Comment by NicolaDonelli** [comment]
For sure the package version could be added to the image tag, and probably we could also change the makefile so that would be done automatically with a single command. I'll amend my PR with your suggestions.
